export const SwitchGroup = 'groupType/SwitchGroups'
export const SetUserInfo = 'user/SetUserInfo'
export const SetMySocket = 'user/SetMySocket'
export const SetToken = 'user/SetToken'
export const GetToken = 'user/GetToken'
export const SetLanguage = 'user/SetLanguage'
export const GetUserInfo = 'user/GetUserInfo'
export const SetIsOnline = 'user/SetIsOnline'
