export const SetGPSList = 'map/SetGPSList'
export const SetMapTempMemberList = 'map/SetMapTempMemberList'
export const SetHasMapTempGroup = 'map/SetHasMapTempGroup'
export const GetIsChina = 'map/GetISChina'
export const SetGpsPoint = 'map/SetGpsPoint'
export const SetIsToCenter = 'map/SetIsToCenter'
